site_name: "artist-app-docs"

nav:
  - Artist App: index.md
      - Getting Started: gettingStarted.md
      - Frontend Architecture: architecture.md
  - Development: development.md

plugins:
  - techdocs-core
