site_name: "artist-app-docs"

nav:
  - Artist App: README.md
      - Getting Started: gettingStarted.md
      - Frontend Architecture: architecture.md
  - Development: development.md
      - How to Test?: index.md

plugins:
  - techdocs-core
